services:
  - type: web
    name: attract-backend
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
      - key: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET
      - key: GROQ_API_KEY
      - key: GROQ_MODEL
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: "production"
