import { useState, useEffect } from "react";
import LeftSidebar from "../components/LeftSidebar";
import MonetizationCard from "../components/MonetizationCard";

import { API_BASE } from "../config/api";

const ads = [
  {
    title: "📈 Performance Insights",
    text: "Get AI-powered performance analysis for better reviews",
    button: "Try Free"
  },
  {
    title: "🎯 Goal Tracking",
    text: "Set and track employee goals effectively",
    button: "Learn More"
  },
  {
    title: "💡 Development Plans",
    text: "Create personalized growth plans for your team",
    button: "Upgrade"
  }
];

export default function PerformanceReviewAnalyzer({ app, isPro = false }) {
  const [currentAd, setCurrentAd] = useState(0);
  const [formData, setFormData] = useState({
    employeeName: "",
    employeeId: "",
    department: "",
    position: "",
    managerName: "",
    reviewPeriod: "Q4 2024",
    reviewType: "Annual",
  });
  const [selfReview, setSelfReview] = useState("");
  const [managerFeedback, setManagerFeedback] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [showPayment, setShowPayment] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [activeTab, setActiveTab] = useState("analyze");
  const [analysisCount, setAnalysisCount] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentAd((prev) => (prev + 1) % ads.length);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleUpgrade = () => {
    setShowPayment(true);
  };

  const processPayment = () => {
    setIsProcessing(true);
    setTimeout(() => {
      setIsProcessing(false);
      setShowPayment(false);
    }, 1500);
  };

  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const analyzeReview = async () => {
    if (!selfReview.trim() && !managerFeedback.trim()) return;

    // Check if pro feature is needed
    if (!isPro && analysisCount >= 3) {
      setShowPayment(true);
      return;
    }

    setIsAnalyzing(true);
    try {
      const res = await fetch(`${API_BASE}/api/performance-review/analyze`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ selfReview, managerFeedback }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Analysis failed");
      setAnalysis(data);
      setAnalysisCount(prev => prev + 1);
      setActiveTab("results");
    } catch (err) {
      setAnalysis({
        overallTone: "Error",
        strengthCount: 0,
        concernCount: 0,
        detectedThemes: ["Analysis failed"],
        suggestedSummary: [err.message || "Please try again"],
        nextSteps: [],
        estimatedRating: 0,
        promotionEligible: false,
        bonusEligible: false,
        generatedAt: new Date().toLocaleString(),
      });
      setActiveTab("results");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const copyReport = () => {
    if (!analysis) return;

    const report = `PERFORMANCE REVIEW ANALYSIS
=============================
Generated: ${analysis.generatedAt}

EMPLOYEE INFORMATION
--------------------
Name: ${formData.employeeName || "[Name]"}
ID: ${formData.employeeId || "[ID]"}
Department: ${formData.department || "[Department]"}
Position: ${formData.position || "[Position]"}
Manager: ${formData.managerName || "[Manager]"}
Review Period: ${formData.reviewPeriod}
Review Type: ${formData.reviewType}

ANALYSIS SUMMARY
---------------
Overall Tone: ${analysis.overallTone}
Estimated Rating: ${analysis.estimatedRating}/5
Strengths Identified: ${analysis.strengthCount}
Development Areas: ${analysis.concernCount}

DETECTED THEMES
---------------
${analysis.detectedThemes.map(t => `• ${t}`).join('\n')}

SUGGESTED SUMMARY
-----------------
${analysis.suggestedSummary.map(p => `• ${p}`).join('\n')}

RECOMMENDED NEXT STEPS
---------------------
${analysis.nextSteps.map((s) => `[${s.type}] ${s.action}`).join('\n')}

RECOMMENDATIONS
---------------
${analysis.promotionEligible ? "✓ Eligible for promotion consideration" : "✗ Not yet ready for promotion"}
${analysis.bonusEligible ? "✓ Eligible for performance bonus" : "✗ Bonus not recommended based on current performance"}

---
Generated by Atract HR Performance Review Helper
`;

    navigator.clipboard.writeText(report);
  };

  return (
    <div className="flex min-h-screen bg-gray-100">
      {/* Left Sidebar */}
      <LeftSidebar 
        app={app} 
        isPro={isPro}
        ads={ads}
        currentAd={currentAd}
        onUpgrade={handleUpgrade}
        onAdChange={setCurrentAd}
      />

      {/* Main Content */}
      <div className="flex-1 ml-80 p-6">
        {/* Payment Modal */}
        {showPayment && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <div className="bg-white rounded-2xl p-6 max-w-md w-full mx-4 shadow-2xl">
              <h3 className="text-xl font-bold text-gray-900">Unlock Performance Review Helper</h3>
              <p className="text-gray-600 mt-2">Get unlimited performance reviews analysis with AI insights</p>
              
              <div className="mt-4 bg-gray-50 rounded-xl p-4">
                <div className="flex justify-between items-center">
                  <span className="text-gray-600">Monthly subscription</span>
                  <span className="text-2xl font-bold text-gray-900">₹299/month</span>
                </div>
                <div className="mt-2 text-sm text-gray-500">
                  • Unlimited analysis<br/>
                  • Detailed recommendations<br/>
                  • Export reports
                </div>
              </div>

              <button
                onClick={processPayment}
                disabled={isProcessing}
                className="w-full mt-4 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-xl font-semibold hover:opacity-90 transition-opacity disabled:opacity-50"
              >
                {isProcessing ? "Processing..." : "Subscribe - ₹299/month"}
              </button>

              <button
                onClick={() => setShowPayment(false)}
                className="w-full mt-3 py-2 text-gray-500 hover:text-gray-700"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* Sticky Header */}
        <div className="sticky top-0 z-10 bg-gray-100 pb-4 -mx-6 px-6">
          <h1 className="text-3xl font-bold text-gray-900">{app?.name || "Performance Review Helper"}</h1>
          <p className="text-gray-600 mt-1">{app?.valueProposition || "Self + manager review drafts"}</p>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-6">
          <button
            onClick={() => setActiveTab("analyze")}
            className={`px-4 py-2 rounded-xl font-medium transition-all ${
              activeTab === "analyze"
                ? "bg-blue-500 text-white"
                : "bg-white text-gray-600 hover:bg-gray-50"
            }`}
          >
            📋 Analyze Review
          </button>
          <button
            onClick={() => setActiveTab("results")}
            className={`px-4 py-2 rounded-xl font-medium transition-all ${
              activeTab === "results"
                ? "bg-blue-500 text-white"
                : "bg-white text-gray-600 hover:bg-gray-50 cursor-pointer"
            }`}
            disabled={!analysis}
          >
            📊 Results {analysis ? "" : "(0)"}
          </button>
        </div>

        {/* Analyze Tab */}
        {activeTab === "analyze" && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
              {/* Employee Info */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Employee Information</h2>
                
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Employee Name</label>
                    <input
                      type="text"
                      name="employeeName"
                      value={formData.employeeName}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="e.g. John Doe"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Employee ID</label>
                    <input
                      type="text"
                      name="employeeId"
                      value={formData.employeeId}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="e.g. EMP001"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Department</label>
                    <input
                      type="text"
                      name="department"
                      value={formData.department}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="e.g. Engineering"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Position</label>
                    <input
                      type="text"
                      name="position"
                      value={formData.position}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="e.g. Senior Developer"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Reporting Manager</label>
                    <input
                      type="text"
                      name="managerName"
                      value={formData.managerName}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="Manager name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Review Period</label>
                    <input
                      type="text"
                      name="reviewPeriod"
                      value={formData.reviewPeriod}
                      onChange={handleInputChange}
                      className="w-full rounded-xl border border-gray-200 px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="e.g. Q4 2024"
                    />
                  </div>
                </div>
              </div>

              {/* Review Inputs */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Review Inputs</h2>
                
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Self-Review Text (Optional)</label>
                    <textarea
                      value={selfReview}
                      onChange={(e) => setSelfReview(e.target.value)}
                      rows={6}
                      className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="Paste employee's self assessment here..."
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Manager Feedback / Comments (Optional)</label>
                    <textarea
                      value={managerFeedback}
                      onChange={(e) => setManagerFeedback(e.target.value)}
                      rows={6}
                      className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="Paste manager's written feedback here..."
                    />
                  </div>

                  <button
                    onClick={analyzeReview}
                    disabled={(!selfReview.trim() && !managerFeedback.trim()) || isAnalyzing}
                    className={`w-full py-3 rounded-xl font-semibold transition-all ${
                      (selfReview.trim() || managerFeedback.trim()) && !isAnalyzing
                        ? "bg-gradient-to-r from-blue-500 to-purple-600 text-white hover:opacity-90 shadow-md"
                        : "bg-gray-200 text-gray-500 cursor-not-allowed"
                    }`}
                  >
                    {isAnalyzing ? "Analyzing..." : (isPro ? "Analyze Performance Review" : `Analyze (${analysisCount}/3 free)`)}
                  </button>
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              <MonetizationCard app={app} />
              
              {/* Quick Stats */}
              <div className="bg-white rounded-2xl shadow-sm p-4">
                <h3 className="font-semibold text-gray-900 mb-3">Review Summary</h3>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-500">Review Type</span>
                    <span className="font-medium">{formData.reviewType}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-500">Period</span>
                    <span className="font-medium">{formData.reviewPeriod}</span>
                  </div>
                </div>
              </div>

              {/* Instructions */}
              <div className="bg-white rounded-2xl shadow-sm p-4">
                <h3 className="font-semibold text-gray-900 mb-3">How It Works</h3>
                <ol className="space-y-2 text-sm text-gray-600">
                  <li className="flex items-start gap-2">
                    <span className="flex-shrink-0 w-5 h-5 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">1</span>
                    <span>Enter employee details</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="flex-shrink-0 w-5 h-5 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">2</span>
                    <span>Paste self/manager reviews</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="flex-shrink-0 w-5 h-5 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">3</span>
                    <span>Get AI-powered insights</span>
                  </li>
                </ol>
              </div>
            </div>
          </div>
        )}

        {/* Results Tab */}
        {activeTab === "results" && analysis && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
              {/* Analysis Results */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-lg font-semibold text-gray-900">Analysis Results</h2>
                  <button
                    onClick={copyReport}
                    className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-200"
                  >
                    Copy Report
                  </button>
                </div>

                {/* Rating Badge */}
                <div className="flex items-center gap-4 mb-6 p-4 bg-gray-50 rounded-xl">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-gray-900">{analysis.estimatedRating}</div>
                    <div className="text-xs text-gray-500">/ 5</div>
                  </div>
                  <div className="flex-1">
                    <div className="font-semibold text-gray-900">Estimated Rating</div>
                    <div className={`inline-block mt-1 px-3 py-1 rounded-full text-sm font-medium ${
                      analysis.overallTone.includes("Positive") ? "bg-green-100 text-green-700" :
                      analysis.overallTone.includes("Needs") ? "bg-red-100 text-red-700" :
                      "bg-amber-100 text-amber-700"
                    }`}>
                      {analysis.overallTone}
                    </div>
                  </div>
                </div>

                {/* Recommendations */}
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className={`p-4 rounded-xl border ${analysis.promotionEligible ? "bg-green-50 border-green-200" : "bg-gray-50 border-gray-200"}`}>
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{analysis.promotionEligible ? "✅" : "❌"}</span>
                      <span className="font-medium">Promotion Eligible</span>
                    </div>
                  </div>
                  <div className={`p-4 rounded-xl border ${analysis.bonusEligible ? "bg-green-50 border-green-200" : "bg-gray-50 border-gray-200"}`}>
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{analysis.bonusEligible ? "✅" : "❌"}</span>
                      <span className="font-medium">Bonus Eligible</span>
                    </div>
                  </div>
                </div>

                {/* Themes */}
                <div className="mb-6">
                  <h3 className="font-semibold text-gray-900 mb-3">Detected Themes</h3>
                  <div className="flex flex-wrap gap-2">
                    {analysis.detectedThemes.map((t, i) => (
                      <span key={i} className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Summary */}
                <div className="mb-6">
                  <h3 className="font-semibold text-gray-900 mb-3">Suggested Summary</h3>
                  <ul className="space-y-2">
                    {analysis.suggestedSummary.map((p, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                        <span className="mt-1 w-1.5 h-1.5 bg-blue-500 rounded-full flex-shrink-0"></span>
                        {p}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Next Steps */}
                <div>
                  <h3 className="font-semibold text-gray-900 mb-3">Recommended Next Steps</h3>
                  <div className="space-y-3">
                    {analysis.nextSteps.map((s, i) => (
                      <div key={i} className="flex items-start gap-3 p-3 bg-gray-50 rounded-xl">
                        <span className={`px-2 py-0.5 rounded text-xs font-semibold ${
                          s.type === "Strength" ? "bg-green-100 text-green-700" :
                          s.type === "Development" ? "bg-red-100 text-red-700" :
                          s.type === "Discussion" ? "bg-blue-100 text-blue-700" :
                          "bg-purple-100 text-purple-700"
                        }`}>
                          {s.type}
                        </span>
                        <span className="text-sm text-gray-900">{s.action}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              <MonetizationCard app={app} />
              
              {/* Stats */}
              <div className="bg-white rounded-2xl shadow-sm p-4">
                <h3 className="font-semibold text-gray-900 mb-3">Analysis Stats</h3>
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-green-50 rounded-xl p-3 text-center">
                    <div className="text-xl font-bold text-green-700">{analysis.strengthCount}</div>
                    <div className="text-xs text-green-600">Strengths</div>
                  </div>
                  <div className="bg-red-50 rounded-xl p-3 text-center">
                    <div className="text-xl font-bold text-red-700">{analysis.concernCount}</div>
                    <div className="text-xs text-red-600">Developments</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
